//! Golden-row tests over the checked-in MRT fixtures (`data/*.mrt`, generated by
//! `data/generate_fixtures.rs`): a TABLE_DUMP_V2 RIB, a BGP4MP update batch
//! (IPv4 + IPv6, standard + large communities), and a deliberately truncated
//! tail record. Asserts the decoded rows and the AS-path / community / INET
//! helpers against known values.

use std::fs::File;
use std::io::BufReader;
use std::net::IpAddr;
use std::str::FromStr;

use bgp_core::aspath;
use bgp_core::decode::{decompress_reader, next_record, Decoder, MrtRow, MsgType};
use std::io::Read;

/// Decode every route/state row from a fixture, returning `(rows, ended_clean)`
/// where `ended_clean` is true on a clean EOF and false on a (truncation) error.
/// The byte source is run through `decompress_reader`, so a `.gz` fixture is
/// transparently inflated first.
fn decode_rows(path: &str) -> (Vec<MrtRow>, bool) {
    let f = File::open(path).unwrap_or_else(|e| panic!("open {path}: {e}"));
    let raw: Box<dyn Read + Send> = Box::new(BufReader::new(f));
    let mut r = decompress_reader(raw).unwrap();
    let mut dec = Decoder::new();
    let mut rows = Vec::new();
    loop {
        match next_record(&mut r) {
            Ok(Some(rec)) => rows.extend(dec.record_rows(rec)),
            Ok(None) => return (rows, true),
            Err(_) => return (rows, false),
        }
    }
}

fn find<'a>(rows: &'a [MrtRow], prefix: &str, peer_asn: u32) -> &'a MrtRow {
    let (addr, len) = split_prefix(prefix);
    rows.iter()
        .find(|r| r.prefix == Some((addr, len)) && r.peer_asn == Some(peer_asn))
        .unwrap_or_else(|| panic!("no row for {prefix} peer {peer_asn}"))
}

fn split_prefix(s: &str) -> (IpAddr, u16) {
    let (a, m) = s.split_once('/').unwrap();
    (IpAddr::from_str(a).unwrap(), m.parse().unwrap())
}

#[test]
fn rib_table_dump_v2_golden() {
    let (rows, clean) = decode_rows("../../data/rib.mrt");
    assert!(clean, "rib.mrt should decode to a clean EOF");
    // Three RIB entries: 203.0.113.0/24 from two peers + 2001:db8:abcd::/48.
    assert_eq!(rows.len(), 3, "rows: {rows:#?}");
    assert!(rows.iter().all(|r| r.msg_type == Some(MsgType::Announce)));

    // IPv4 prefix from AS65001: prepended path + large community.
    let r = find(&rows, "203.0.113.0/24", 65001);
    assert_eq!(
        r.as_path.as_deref(),
        Some(&[65001, 64500, 64500, 64512][..])
    );
    assert_eq!(r.origin_asn, Some(64512));
    assert_eq!(r.next_hop, Some(IpAddr::from_str("192.0.2.1").unwrap()));
    let comms = r.communities.as_ref().unwrap();
    assert!(comms.contains(&"65001:100".to_string()));
    assert!(comms.contains(&"65001:1:2".to_string())); // large community
                                                       // AS-path helpers over the decoded path.
    let path = r.as_path.as_ref().unwrap();
    assert_eq!(aspath::path_length(path), 4);
    assert_eq!(aspath::origin_asn(path), Some(64512));
    assert_eq!(aspath::as_path_prepends(path), 1); // the doubled 64500
    assert!(aspath::path_contains(path, 64500));
    assert!(!aspath::path_contains(path, 99999));

    // IPv6 prefix.
    let r6 = find(&rows, "2001:db8:abcd::/48", 65001);
    assert_eq!(r6.next_hop, Some(IpAddr::from_str("2001:db8::1").unwrap()));
    assert_eq!(r6.origin_asn, Some(64600));
}

#[test]
fn updates_bgp4mp_golden() {
    let (rows, clean) = decode_rows("../../data/updates.mrt");
    assert!(clean, "updates.mrt should decode cleanly");
    assert_eq!(rows.len(), 3, "rows: {rows:#?}");

    let announces = rows
        .iter()
        .filter(|r| r.msg_type == Some(MsgType::Announce))
        .count();
    let withdraws = rows
        .iter()
        .filter(|r| r.msg_type == Some(MsgType::Withdraw))
        .count();
    assert_eq!((announces, withdraws), (2, 1));

    // The withdrawal: prefix present, no path/next_hop.
    let w = rows
        .iter()
        .find(|r| r.msg_type == Some(MsgType::Withdraw))
        .unwrap();
    assert_eq!(w.prefix, Some(split_prefix("203.0.113.0/24")));
    assert!(w.as_path.is_none());
    assert!(w.next_hop.is_none());

    // The IPv4 announce carries the standard + large communities.
    let a = find(&rows, "203.0.113.0/24", 65001);
    let comms = a.communities.as_ref().unwrap();
    assert!(comms.contains(&"65001:1:2".to_string()));
}

#[test]
fn gzip_fixture_matches_plain() {
    let (plain, _) = decode_rows("../../data/updates.mrt");
    let (gz, clean) = decode_rows("../../data/updates.mrt.gz");
    assert!(clean);
    assert_eq!(plain, gz, "gzip decode must match the plain stream");
}

#[test]
fn truncated_tail_yields_partial_then_error() {
    // The truncated RIB decodes its leading record(s), then the chopped tail
    // surfaces as a (non-clean) error rather than a panic — the worker turns
    // this into an error row.
    let (rows, clean) = decode_rows("../../data/truncated.mrt");
    assert!(!clean, "a truncated tail must NOT report a clean EOF");
    assert!(
        !rows.is_empty(),
        "the leading intact record(s) should still decode"
    );
}
